-- Billboard constants

return {
	["Billboard"] = {
		["Personal"] = "Personal",
		["SkyWars"] = "SkyWars",
		["EggWars"] = "EggWars",
		["Timer"] = "Timer",
	},
	["BillboardSize"] = {
		["Large"] = "Large",
		["Small"] = "Small",
	},
} :: {
	["Billboard"]: {
		["Personal"]: string,
		["SkyWars"]: string,
		["EggWars"]: string,
		["Timer"]: string,
	},
	["BillboardSize"]: {
		["Large"]: string,
		["Small"]: string,
	},
}
